# Generated by Django 5.1.6 on 2025-03-02 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="activated_invite_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activated_by",
                to="users.invitecode",
                verbose_name="Активированный инвайт-код",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="invite_code",
            field=models.CharField(
                blank=True,
                default="",
                max_length=6,
                unique=True,
                verbose_name="Инвайт-код",
            ),
        ),
    ]
