# Generated by Django 5.1.6 on 2025-03-08 08:46

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_first_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                (
                    "code",
                    models.CharField(
                        default=users.models.generate_login_code, max_length=4
                    ),
                ),
                ("is_actual", models.BooleanField(default=True)),
            ],
        ),
    ]
