# Generated by Django 5.1.6 on 2025-03-09 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_create_login_code_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="linked_users",
            field=models.ManyToManyField(
                blank=True, related_name="linked_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
